name: zHomes
version: '${project.version}'
main: me.leonardo.zhomes.Main
authors: [yLeoft]
softdepend:
  - PlaceholderAPI


commands:
  sethome:
    aliases: [ seth, setarhome, setarh ]
    description: Set a home
  delhome:
    aliases: [ delh, deletehome, deletarhome, deletarh]
    description: Delete a home
  home:
    description: Go to a home