name: zHomes
version: '${project.version}'
main: me.leonardo.zhomes.Main
authors: [yLeoft]
website: https://github.com/yL3oft/zHomes
softdepend:
  - PlaceholderAPI


commands:
  sethome:
    aliases: [ seth, setarhome, setarh ]
    description: Set a home
  delhome:
    aliases: [ delh, deletehome, deletarhome, deletarh]
    description: Delete a home
  home:
    description: Go to a home
  homes:
    aliases: [ myhomes ]
    description: See all your homes
  zhomes:
    aliases: [ zhome ]
    description: Configurate the plugin via command


permissions:
  zhomes.commands.sethome:
    description: Permission to execute /sethome
    default: true
  zhomes.commands.delhome:
    description: Permission to execute /delhome
    default: true
  zhomes.commands.home:
    description: Permission to execute /home
    default: true
  zhomes.commands.homes:
    description: Permission to execute /homes
    default: true
  zhomes.commands.zhomes:
    description: Permission to execute /zhomes
    default: false