name: zHomes
version: '1.3.4'
main: me.yleoft.zHomes.Main
author: yLeoft
website: 'https://github.com/yL3oft/zHomes'
api-version: "1.13"
softdepend:
  - PlaceholderAPI
  - Vault
  - Essentials
  - UltimateHomes
  - Sethome
  - Xhomes
folia-supported: true
commands: {}
permissions: {}