name: Modrinth Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Get project version from POM
        id: get_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Upload to Modrinth
        run: |
          curl -X POST https://api.modrinth.com/v2/version \
          -H "Authorization: ${{ secrets.MODRINTH_TOKEN }}" \
          -H "Content-Type: multipart/form-data" \
          -F "data={
            \"name\": \"zHomes ${{ steps.get_version.outputs.version }}\",
            \"version_number\": \"${{ steps.get_version.outputs.version }}\",
            \"project_id\": \"zhomes-dev\",
            \"version_type\": \"alpha\",
            \"loaders\": [\"bukkit\", \"paper\", \"spigot\", \"folia\", \"purpur\"],
            \"game_versions\": [
              \"1.8\", \"1.8.1\", \"1.8.2\", \"1.8.3\", \"1.8.4\", \"1.8.5\", \"1.8.6\", \"1.8.7\", \"1.8.8\", \"1.8.9\",
              \"1.9\", \"1.9.1\", \"1.9.2\", \"1.9.3\", \"1.9.4\",
              \"1.10\", \"1.10.1\", \"1.10.2\",
              \"1.11\", \"1.11.1\", \"1.11.2\",
              \"1.12\", \"1.12.1\", \"1.12.2\",
              \"1.13\", \"1.13.1\", \"1.13.2\",
              \"1.14\", \"1.14.1\", \"1.14.2\", \"1.14.3\", \"1.14.4\",
              \"1.15\", \"1.15.1\", \"1.15.2\",
              \"1.16\", \"1.16.1\", \"1.16.2\", \"1.16.3\", \"1.16.4\", \"1.16.5\",
              \"1.17\", \"1.17.1\",
              \"1.18\", \"1.18.1\", \"1.18.2\",
              \"1.19\", \"1.19.1\", \"1.19.2\", \"1.19.3\", \"1.19.4\",
              \"1.20\", \"1.20.1\", \"1.20.2\", \"1.20.3\", \"1.20.4\",
              \"1.21\", \"1.21.1\"
            ]
          };type=application/json" \
          -F "file=@target/zHomes-${{ steps.get_version.outputs.version }}.jar"